### ISSUE TITLE
ms_account_skin.py的报错

### ISSUE THREAD

**Issue by DanielDual** [Sharll-large/FMCL#12]
### Describe the bug
在D:\FMCL\FMCLCore\auth\ms_account_skin.py里的报错：
  File "D:\FMCL\FMCLCore\auth\ms_account_skin.py", line 13, in <module>
    def get_skin_of(name: str, uuid: str, refresh: bool = False) -> bytes | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

***Notice: Please provide the Minecraft version, mods and mods loader (if installed), Java version and other information so that we can fix issues faster and easier.***

### FMCL logs
the important part of launcher log
下载都没下载呢（（（

### Other launcher's launch script
If other launchers can not launch too, please close the issue.

**Comment by AGJ-smart** [comment]
能提供 Python 运行环境信息吗

**Comment by DanielDual** [comment]
3.9
3.10不好看（（
且两个装一起会有问题

**Comment by pxinz** [comment]
你的python版本不支持这种注解（  
以后可能会出无注解版 就会好一些

**Comment by DanielDual** [comment]
> 你的python版本不支持这种注解（ 以后可能会出无注解版 就会好一些

谢谢那么久还回来回答
