### ISSUE TITLE
讨论是否要更换UI库

### ISSUE THREAD

**Issue by Sharll-large** [Sharll-large/FMCL#15]
tkinter看起来似乎太烂了，影响了开发效率和美观性

因此做出投票决定是否更换UI库

新的UI库要求如下：

1. UI库不能过于庞大（使用pyinstaller/nuitka打包后体积）
2. UI库需要跨平台（win/linux/mac）
3. 要有文档，易于编写（总不能比tk还烂）

可以说说各位的想法

**Comment by Sharll-large** [comment]
DearPyGUI

**Comment by pxinz** [comment]
TUI包解君愁（

**Comment by pxinz** [comment]
textual（

**Comment by Sharll-large** [comment]
textual其实很大

**Comment by pxinz** [comment]
像隔壁SMCL一样自研TUI（（（（（（（（（（（（（（（（（（（（（（（（（（（（（

**Comment by mc-124** [comment]
tui好像比tk还丑
我投反对，我认为tkinter足够了（因为凡是漂亮点的体积都能上天）

**Comment by mc-124** [comment]
刚才看了下，dearpygui的体积达到了10MB，打包后超过了一个BakaXL

**Comment by Sharll-large** [comment]
> 刚才看了下，dearpygui的体积达到了10MB，打包后超过了一个BakaXL

pyinstaller+upx, py310 64位我这边是6M

**Comment by Sharll-large** [comment]
> tui好像比tk还丑 我投反对，我认为tkinter足够了（因为凡是漂亮点的体积都能上天）

得解决一下闪烁和拖影问题

**Comment by mc-124** [comment]
> > 刚才看了下，dearpygui的体积达到了10MB，打包后超过了一个BakaXL
> 
> pyinstaller+upx， py310 64位我这边是6M

我那边可能是因为在linux打包导致的

**Comment by Sharll-large** [comment]
> > > 刚才看了下，dearpygui的体积达到了10MB，打包后超过了一个BakaXL
> > 
> > 
> > pyinstaller+upx， py310 64位我这边是6M
> 
> 我那边可能是因为在linux打包导致的

你可能没有upx？

**Comment by mc-124** [comment]
> > > > 刚才看了下，dearpygui的体积达到了10MB，打包后超过了一个BakaXL
> > > 
> > > 
> > > pyinstaller+upx， py310 64位我这边是6M
> > 
> > 
> > 我那边可能是因为在linux打包导致的
> 
> 你可能没有upx？

可能吧

**Comment by Sharll-large** [comment]
我真服了，不是不好用就是太大

**Comment by Sharll-large** [comment]
我的天。。

**Comment by mc-124** [comment]
> 我真服了，不是不好用就是太大
别找了，只有tkinter合适

**Comment by mc-124** [comment]
> 我真服了，不是不好用就是太大

别找了，只有tkinter合适

**Comment by Sharll-large** [comment]
@mc-124 你方便下载FMCL源码试试能不能跑吗

**Comment by Sharll-large** [comment]
继续采用tkinter，或考虑基于tkinter的库（TinUI / PySimpleGUI）

**Comment by mc-124** [comment]
能跑啊

> @mc-124 你方便下载FMCL源码试试能不能跑吗

**Comment by mc-124** [comment]
@Sharll-large 
发现问题：FMCLView、core.local、core没有__init__.py导致无法导入

**Comment by mc-124** [comment]
@Sharll-large 你这把__init__删完了运行个毛
