### ISSUE TITLE
Pyinstaller打包FMCL时体积过大

### ISSUE THREAD

**Issue by Sharll-large** [Sharll-large/FMCL#17]
原因是pyperclip中导入了pyqt库，pyinstaller把pyqt包进去了。。

**Comment by pxinz** [comment]
迫真吧你自己改（

**Comment by Sharll-large** [comment]
pyperclip用于微软登录得设备码自动复制，但是目前大多情况下可以简化登录流程，复制设备码为少数情况，考虑弃用pyperclip将少数情况改为手动复制
