### ISSUE TITLE
添加pyi文件

### ISSUE THREAD

**Issue by Sharll-large** [Sharll-large/FMCL#21]
@pxinz 没怎么了解过，添加pyi文件，会不会减小开发难度HUM

**Comment by Sharll-large** [comment]
pycharm好像可以解析这玩意

**Comment by mc-124** [comment]
我认为不大需要，在代码里多打点''''''字符串注释就行
一般pyi都是用在pyd和so上的，很少见有人给py写pyi，因为py本身就可以被IDE解析，而不是像pyd和so那样无法解析

**Comment by mc-124** [comment]
给纯py添加pyi开发难度不会减小，反而会更麻烦
