### ISSUE TITLE
启动1.19.3-Fabric的时候出现错误

### ISSUE THREAD

**Issue by AGJ-smart** [Sharll-large/FMCL#5]
启动1.19.3 Fabric版本的时候出现问题.  启动器错误码=_1_.

**模组列表：**

1. fabric-api-0.70.0+1.19.3
2. ferritecore-5.1.0-fabric
3. indium-1.0.12+mc1.19.3
4. iris-mc1.19.3-1.5.1
5. lithium-fabric-mc1.19.3-0.10.4
6. sodium-extra-0.4.16+mc1.19.3-build.91
7. sodium-fabric-mc1.19.3-0.4.8+build.22

**错误日志:**
[FMCL.log](https://github.com/Sharll-large/FMCL/files/10421859/FMCL.log)
[fabricloader.log](https://github.com/Sharll-large/FMCL/files/10421860/fabricloader.log)

**Comment by AGJ-smart** [comment]
**补充说明：**

在版本隔离打开的情况下，会直接启动器错误码=1报错；

在版本隔离关闭的情况下，会先弹出fabric的报错界面：[fabric报错界面，日志好像是前面的comment里面的fabricloader.log](https://user-images.githubusercontent.com/73345622/212581908-0dc4fa3c-16a4-4cc4-8ef3-91698be0f413.png)，然后再错误码=1.

**Comment by Sharll-large** [comment]
暂时无法复现错误

**Comment by pxinz** [comment]
galaxy brain

**Comment by Sharll-large** [comment]
原因是命令行过长，可以尝试用浅一点的路径解决。

**Comment by AGJ-smart** [comment]
哦买噶
[galaxy_brain](https://user-images.githubusercontent.com/73345622/213436552-ce5f067e-5892-45a5-abdc-69122da8f8f4.png)
