### ISSUE TITLE
Ubuntu上的微软账户登录问题和一个启动问题

### ISSUE THREAD

**Issue by AGJ-smart** [Sharll-large/FMCL#6]
1. 登录Microsoft账户的时候会***400 Bad Request***，但是在Windows上不会

2. 启动1.12.2-Optifine的时候报错，启动器报错码=_1_；
启动器日志：[FMCL.log](https://github.com/Sharll-large/FMCL/files/10426028/FMCL.log)；
版本下载来源是HMCL

**Comment by Sharll-large** [comment]
可以发一下latest.log之类的mc日志吗？

**Comment by Sharll-large** [comment]
运行一下：

**Comment by Sharll-large** [comment]
import platform

**Comment by Sharll-large** [comment]
platform.platform()

**Comment by Sharll-large** [comment]
如果你使用Virtual Box创建虚拟机运行Ubuntu，那很正常，这玩意没显卡驱动

**Comment by Sharll-large** [comment]
第一个马上修

**Comment by AGJ-smart** [comment]
> 如果你使用Virtual Box创建虚拟机运行Ubuntu，那很正常，这玩意没显卡驱动

我用的是VMware Workstation 16 Player（仅用于非商业用途）

**Comment by AGJ-smart** [comment]
> platform.platform()

![图片](https://user-images.githubusercontent.com/73345622/212782548-ede12485-9830-4a7f-a7ab-8eb9ae73c9e5.png)
![图片](https://user-images.githubusercontent.com/73345622/212782691-f248043c-e92a-408d-8e72-a15d34a1d79e.png)

**Comment by Sharll-large** [comment]
已解决
