### ISSUE TITLE
启动游戏后生成了多余的文件夹

### ISSUE THREAD

**Issue by pxinz** [Sharll-large/FMCL#9]
**Describe the bug**
我使用fmcl启动带有CustomSkinLoader，Sodium，Lithium等模组的1.17 Farbic版mc，  
之后，我在__main__.py同目录下发现了新增的三个文件夹：config，CustomSkinLoader，logs  
这三个都是mc本体和模组创建的文件夹，我觉得这应该是工作目录的问题

**FMCL logs**
我认为这里给log没有多大帮助罢

**Other launcher's launch script**
懒得生成（破哦啊

**Comment by AGJ-smart** [comment]
你坡真罢（直球哦买噶

**Comment by AGJ-smart** [comment]
撅

**Comment by pxinz** [comment]
嗯我自己修好了
